### ISSUE TITLE
CORS ?

### ISSUE THREAD

**Issue by julestruong** [bap-node-microframework/node-microframework#19]
/home/vagrant/link-calendar/api/node_modules/bap-node-microframework-cors/dist/app/CorsPlugin.js:13
        core_1.Container.get('app').use(cors(this.instance));
                                                 ^

TypeError: Cannot read property 'get' of undefined
    at new CorsPlugin (/home/vagrant/link-calendar/api/node_modules/bap-node-microframework-cors/dist/app/CorsPlugin.js:13:50)
    at Application.registerPlugin (/home/vagrant/link-calendar/api/node_modules/bap-node-microframework/dist/core/application.js:54:30)
    at Object.<anonymous> (/home/vagrant/link-calendar/api/dist/app/app.js:34:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:160:18)
    at node.js:456:3

**Comment by julestruong** [comment]
@nicolanrizzo ???

**Comment by nicolanrizzo** [comment]
It's the old version of the CORS module. You have to update it:

https://github.com/bap-node-microframework/node-microframework-cors/blob/master/src/app/CorsPlugin.ts#L15

**Comment by julestruong** [comment]
my bad
